name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: '20 20 * * *'

permissions:
  contents: write

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
          SCOOP_BRANCH: develop
          THROW_ERROR: 0
