name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: '20 * * * *'

permissions:
  contents: write

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
      - name: Show rate limit for GitHub API (Before)
        shell: powershell
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          USER_EMAIL: 67540662+verymucho@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SKIP_UPDATED: 1
          SCOOP_GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SCOOP_BRANCH: develop
          THROW_ERROR: 0
      - name: Show rate limit for GitHub API (After)
        shell: powershell
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
